version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      # Ignore all major updates for all dependencies.
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      npm-updates:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-updates:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
